### ISSUE TITLE
Option to not include path in message

### ISSUE THREAD

**Issue by april83c** [causaly/zod-validation-error#134]
I want to use this library, but I don't want the `message` to include the `at "path"` part next to every error — is there a way to do this? If not, could it be added?

For example: right now, it gives me `message` `Namespace must be 2 to 16 characters long at "namespace"` (with my custom error text defined in Zod schema). I'd like it to just be `Namespace must be 2 to 16 characters long` (without the path)

**Comment by thanoskrg** [comment]
Hi @april83c, at the moment modifying this behaviour is not feasible. Here is the part of the code that deals with it:

https://github.com/causaly/zod-validation-error/blob/9df70c46964a13106fbc81efafe5e225207b2ef5/lib/ValidationError.ts#L63

@jmike @nikoskalogridis is this something we could consider adding as an extra option in the API?

**Comment by jmike** [comment]
We could add an additional option to `FromZodIssueOptions`, namely `includePathInfo: boolean` and pass it down to `getMessageFromZodIssue`. It should be `true` by default in order to be backwards-compatible.

TBH I find the request to be somewhat of a corner-case, but It's easy to implement and doesn't require a breaking change. So I do not have a problem.
